Extension { #name : #ToElement }

{ #category : #'*Toplo-Serialization-Stash' }
ToElement >> allSetterAndGettersForMyStashMargin [

	<stashAccessors>
	^ {  }
]

{ #category : #'*Toplo-Serialization-Stash' }
ToElement >> allSetterAndGettersForMyStashPadding [

	<stashAccessors>
	^ {  }
]

{ #category : #'*Toplo-Serialization-Stash' }
ToElement >> allSetterAndGettersForMyStashVisuals [

	<stashAccessors>
	^ {  }
]
